# Generated by Django 4.1 on 2023-06-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_contrasena_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
