# Generated by Django 4.1 on 2023-06-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_tipomaterial_cod_tipo_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cod_material',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
