# Generated by Django 4.1 on 2023-06-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_material_cod_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='cod_cuenta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
