# Generated by Django 4.1 on 2023-06-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_cuenta_cod_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
