# Generated by Django 4.1 on 2023-06-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_usuario_apellido_usuario_correo_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cod_tra',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
